def obter_todos_os_kaomojis():
    kaomoji_dict = {
        "feliz": "(ﾉ^ヮ^)ﾉ*:・ﾟ✧",
        "triste": "(╥_╥)",
        "animada": "ヽ(°〇°)ﾉ",
        "zangada": "(╯°□°）╯︵ ┻━┻",
        "surpresa": "Σ(°ロ°)",
        "apaixonada": "(´∀｀)♡",
        "confusa": "¯\_(ツ)_/¯",
        "envergonhada": "(//▽//)",
        "grata": "( ˘ ³˘)♥",
        "aliviada": "(￣▽￣)ノ",
        "decepcionada": "ಥ_ಥ",
        "cansada": "(╯︵╰,)",
        "orgulhosa": "(｡♥‿♥｡)",
        "contente": "(*˘︶˘*)",
        "nervosa": "(；￣Д￣)",
        "entediada": "(¬_¬)",
        "brincalhona": "(◕‿◕✿)",
        "curiosa": "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
        "esperançosa": "(*^‿^*)",
        "tímida": "(〃ω〃)",
        "divertida": "(￣ω￣)",
        "alegre": "ヾ(´▽｀;)ゝ",
        "boba": "(ﾉ≧∀≦)ﾉ",
        "corada": "(⁄ ⁄•⁄ω⁄•⁄ ⁄)",
        "sonhadora": "(￣з￣)",
        "rabugenta": "(`へ´*)ノ",
        "chique": "(◔◡◔)",
        "desesperada": "(´；д；`)",
        "atrevida": "┐(´д`)┌",
        "zen": "┏(-_-)┛┗(-_- )┓",
        "animada": "( ﾟ∀ﾟ)ﾉ",
        "nostálgica": "( ˘︹˘ )",
        "energética": "ヾ(＾-＾)ノ",
        "encantada": "(✿◠‿◠)",
        "melancólica": "(´･_･`)",
        "fofinha": "(⁄ ⁄>⁄ ▽ ⁄<⁄ ⁄)",
        "amedrontada": "(⊙_⊙)",
        "preocupada": "( ´•̥̥̥ω•̥̥̥` )",
        "desajeitada": "(´・ω・`)",
        "sonolenta": "(ᴗ˳ᴗ)",
        "sarcastica": "(￢_￢)",
        "sortuda": "(ﾉ≧∀≦)ﾉ",
        "intrigada": "(´・_・`)",
        "solitária": "(´；ω；`)",
        "aconchegante": "(´∩｡• ᵕ •｡∩`)",
        "envergonhada": "(/ω＼)",
        "aterrorizada": "∑(O_O；)",
        "relaxada": "꒰ ˆ ॢ꒵ ॢˆ꒱",
        "surpresa": "(ﾟoﾟ)",
        "acordando": "ᗜԅ(⇀︿⇀)ᓄ",
        "yandere": "( ´-ω･)︻┻┳══━一",
        "feita": "￢o(￣-￣ﾒ)",
        "cantando": "♪♪♪ ヽ(ˇ∀ˇ )ゞ",
        "fones de ouvido": "♬♫♪◖(● o ●)◗♪♫♬",
        "trapaceira": "( ＾▽＾)っ✂╰⋃╯	",
        "namorado": "( • )( • )ԅ(≖‿≖ԅ)",
        "afogando": "‿︵‿︵‿︵‿ヽ(°□° )ノ︵‿︵‿︵‿︵",
        "chuva": "｀、ヽ｀ヽ｀、ヽ(ノ＞＜)ノ ｀、ヽ｀☂ヽ｀、ヽ",
        "apontando": "(　･ω･)☞	",
        "nerd": "(⌐■_■)",
        "comendo": "(๑ᵔ⤙ᵔ๑)",
        "faminta": "(￣﹃￣)",
        "fumando": "౦０o ｡ (‾́。‾́ )y~~",
        "facepalm": "(－‸ლ)",
        "rendendo-se": "(oT-T)尸",
        "suspeita": "( ͠° ͟ʖ ͡°)",
        "x1": "( ノ-_-)ノﾞ_□ VS □_ヾ(^-^ヽ)",
        "jogadoras": "(˙ω˙)🎮(˙∀˙)🎮",
        "completa": "(っ˘ڡ˘ς)	",
        "churrasco": "( ・・)つ―{}@{}@{}-	",
        "luta": "Q(`⌒´Q)",
        "tsundere": "(//¬//_//¬//'')ԅ(￣ε￣ԅ)",
        "amigas": "ヽ(≧◡≦)八(o^ ^o)ノ",
        "miga": " ٩(๑･ิᴗ･ิ)۶٩(･ิᴗ･ิ๑)۶",
        "turma": "(っ˘▽˘)(˘▽˘)˘▽˘ς)",
        "dormindo": "(￣ρ￣)..zzZZ",
        "correndo": "─=≡Σ((( つ＞＜)つ",
        "peido": "ε===(っ≧ω≦)っ",
        "escrevendo": "__φ(．．;)",
        "escondendo": "┬┴┬┴┤(･_├┬┴┬┴",
        "sangramento nasal": "(￣ﾊ￣*)",
        "pedindo desculpas": "(*_ _)人",
        "simping": "(シ_ _)シ",
        "piscadinha": "(｡•̀ᴗ-)✧",
        "abraço": "(⊃｡•́‿•̀｡)⊃",
        "beijo": "(づ￣ ³￣)づ",
        "oi": "(・∀・)ノ",
        "franzindo a testa": "(ᓀ ᓀ)",
        "gata": "ฅ(=^･ｪ･^=)ฅ",
        # Animais
        "gato": "(=^‥^=)",
        "cachorro": "U・ᴥ・U",
        "urso": "ʕ·ᴥ·ʔ",
        "coelho": "૮₍ ˶• ༝ •˶ ₎ა",
        "rato": "<:3 )~",
        "porco": "( ´(00)ˋ )",
        "vaca": "｡ﾟ(ﾟ´(00)`ﾟ)ﾟ｡",
        "cavalo": " (◕(‘人‘) ◕)",
        "ovelha": " Ꮚ¯ꈊ¯Ꮚ",
        "macaco": " @(´･ｪ･`)@",
        "pinto": "( ˋ Θ ´ )",
        "pato": " ⊹⋛⋋(◐⊝◑)⋌⋚⊹",
        "sapo": " Ꮚ[◐ o ◑ ]Ꮚ",
        "tigre": " ฅ^•ﻌ•^ฅ",
        "leão": " (,,^・⋏・^,,)",
        "elefante": " @ •́||•̀ @ ",
        "panda": " ʕ·͡ᴥ·ʔ ",
        "coalas": " ʢٛ•ꇵٛ•ʡ ",
        "cobra": " ～>`)～～～ ",
        "tartaruga": " ,=,e ",
        "peixe": "><(((('>",
        "polvo": "~/\( •̀ ω •́ )/\~",
        "tubarão": " 𓆝",
        "golfinho": " (Q )) >",
        "baleia": " . ><(((.______.)",
        "passarinho": " ⊹⋛⋋( ՞ਊ ՞)⋌⋚⊹",
        "coruja": " [ᓀ˵◇˵ᓂ] ",
        "pinguim": " (•͈⌔•͈⑅) ",
        "morcego": " /|\ ^._.^ /|\ ",
        "aranha": "/╲/\╭[ ᴼᴼ ౪ ᴼᴼ]╮/\╱\ ",
        "borboleta": " ƸӜƷ ",
        "abelha": "¸.·´¯`·¸¸. ི♥ྀ",
        "caramujo": " _@/ ",
        "formiga": " ૂི•̮͡• ૂ ྀ ",
        "joaninha": " * ूི-̭͡- ૂ ྀ⁎ꂚᴉᴉᴉ ",
        "libélula": ">ï<",
        "lagarta": "𓆙",
        "vagalume": "✨ ᙙᙖ ",
        "unicórnio": " (◕(‘人‘) ◕) ∋,｡･:*:･ﾟ’☆",
        "dragão": " ᏊˊꍓˋᏊ ",
        "fênix": " 炎炎(o｀Θ´)o*:･ﾟ’☆ ",
        "fada": " (⊃｡•́‿•̀｡)⊃━✿✿✿✿✿✿",
        "yeti": "༼☯﹏☯༽",
        "kraken": "ԅ( ˘ω˘ ԅ)",
        "fantasma": "༼ つ ◕_◕ ༽つ",
        "alien": "(◣ _ ◢)",
        "anjo": "ଘ(੭ˊᵕˋ)੭* ੈ✩‧₊˚ ",
        "zumbis": "乁( x ω x乁)",
        "lebre": "／(˃ᆺ˂)＼",
    }
    return kaomoji_dict

def obter_kaomoji(sentimento_ou_animal):
    kaomoji_dict = obter_todos_os_kaomojis()
    return kaomoji_dict.get(sentimento_ou_animal.lower(), "Desculpe, não tenho um kaomoji para esse sentimento ou animal.")

if __name__ == "__main__":
    while True:
        entrada_usuario = input("Digite um sentimento, o nome de um animal ou 'todos' para listar tudo, ou 'sair' para encerrar: ")
        if entrada_usuario.lower() == 'sair':
            print("Encerrando...")
            break
        elif entrada_usuario.lower() == 'todos':
            todos_os_kaomojis = obter_todos_os_kaomojis()
            print("Kaomojis disponíveis:")
            for chave, valor in todos_os_kaomojis.items():
                print(f"{chave}: {valor}")
        else:
            kaomoji = obter_kaomoji(entrada_usuario)
            print("Kaomoji para o sentimento '{}' ou animal '{}': {}".format(entrada_usuario, entrada_usuario, kaomoji))
